### ISSUE TITLE
Unsaved configuration

### ISSUE THREAD

**Issue by THEDARKK** [JohnTheGr8/upScreen#2]
Hello, thank you for this great tool.

I'd like why, when I uncheck open the link in the browser, it automatically recovers.
I use windows 10.

Thank You

**Comment by JohnTheGr8** [comment]
Hey,

The options in the right-click menu are meant to be temporary. Just like, when you change an account and/or folder from the menu, they only change temporarily, but you can set the defaults in the options form.

However, setting defaults for 'open link in browser' and 'copy link to clipboard' in the options is not possible right now. Should I add that option?

**Comment by THEDARKK** [comment]
Hi, thank you for that answer, its can be helpful.
Thank You

**Comment by JohnTheGr8** [comment]
Found some time to add a couple more features to include with this in a release. Sorry it took so long!
